### PR TITLE
fix(ui): Fix for dark theme

### PR DESCRIPTION
**Pull request by lupusA**
Hi, 

this PR should fix the dark theme that is currently in production. 

Cheers,

### CODE REVIEW

**Comment by lupusA** [comment]
Hi @jkowalski, 

maybe a rebuilt does it already. I've rebuilt it locally and it seems to work without the PR

image

**Comment by ptandler** [comment]
Hi @lupusA, is this about this issue in the current v0.14.0? i.e. the wrong colors in the striped table and the missing dark mode in some (all?) input fileds? I was just about to file an issue and then found your PR.

Screenshot_20230917_103540

**Comment by lupusA** [comment]
Hi @ptandler,

Yeah it is, but I think it just needs to be rebuild. I was not able to reproduce it with a local new build of htmlui.

I think this PR is not necessary.

Cheers,

**Comment by lupusA** [comment]
Hi @ptandler, 

the input fields need an overhaul for the dark theme. We can use this PR for it. 

Cheers

**Comment by lupusA** [comment]
@jkowalski , @ptandler 
This is how it should look like:

https://github.com/kopia/htmlui/assets/37236531/dbec2dde-c628-4ec0-8d13-14c08d04115e

Please test it.

Cheers,

**Pull request merged**
