### PR TITLE
Added directory breadcrumb buttons to see path and navigate back

### PR DESCRIPTION
**Pull request by ptandler**
Added directory breadcrumbs to
- be able to view the current path one came to the current directory
- be able to quickly navigate upwards

Before, you need to click `Return` several times - and you could not see the path.

Please note, this is the first time I'm using React, so I'd be glad if someone could have a look and check if this is the way to go.

### CODE REVIEW

**Comment by jkowalski** [comment]
I took a quick look, the idea is great, but we need to work on layout:

I suggest using links via React Breadcrumbs component: https://react-bootstrap.github.io/components/breadcrumb/
Also, we're displaying the OID, which does not seem necessary, at least on screen (can be in a tooltip).

**Comment by ptandler** [comment]
Thanks you for your feedback, as soon as I have some spare time, I'll give this a try.

WRT the OID, I agree that it is distracting in most cases, but I'd like to have it in a way that I could copy it if required (e.g. for some CLI actions). Maybe this works with a tooltip.

**Comment by ptandler** [comment]
@jkowalski I now had time to do the changes you suggested. What do you think?
I like it better :slightly_smiling_face: 

Screenshot_20230611_160704
Screenshot_20230611_161045

**Comment by jkowalski** [comment]
This is very cool, can you rebase to latest main and we can merge...

**Comment by ptandler** [comment]
@jkowalski merged main

**Pull request merged**
