### PR TITLE
Added ECC fields to repo create and status

### PR DESCRIPTION
**Pull request by pescuma**
This depends on https://github.com/kopia/kopia/pull/2314

I could not find something similar to `.Hide()` that was used in the cli, so when this is merged everyone will be able to enable ECC.

### CODE REVIEW

**Comment by jkowalski** [comment]
The UI for creating repository is getting pretty dense:

image

We should probably split this into multiple lines:

Encryption/Hash/Splitter
ECC/Overhead/FormatVersion
Username/Hostname

Same thing for the status page, which is already very dense.

We need a default to be not enable ECC. Also, I created a repo using this PR + https://github.com/kopia/kopia/pull/2314 and it did not enable ECC.

BTW to test those things in tandem, you can run this in one terminal:

```
$ kopia server start --insecure --without-password --disable-csrf-token-checks
```

And in another:

```
$ npm run start
```

**Comment by pescuma** [comment]
Yeah, the UI was not pretty, but I didn't know how you'd prefer it. I've changed them, screenshots bellow. If you want, I can add the "Repository Format" field in the repository status screen.

> Also, I created a repo using this PR + https://github.com/kopia/kopia/pull/2314 and it did not enable ECC.

Strange, I just tested here and it worked. Did you change the ECC Overhead (%) to be greater than 0? By default it is 0, what disables ECC:

image

image

image

**Comment by jkowalski** [comment]
Can we pivot the second line so that we have `Repository Format`, `Error Correction Overhead (0=disabled)`, and `Error Correction Algorithm` in this order?

I would also replace the overhead field with a dropdown, with some common options:

* `disabled` (default)
* `1%`
* `5%`
* `10%`

Can we also put some "experimental" label next to ECC and maybe add help text below it, something like "Error correction can help protect from certain kinds of data corruption due to spontaneous bit flips in the storage media. Click here to learn more." pointing at some docs page on https://kopia.io

**Comment by pescuma** [comment]
Done. I added 2% because that is the one I intend to use. Also, I added the format version info in the repository status, because it was bugging me that it was not symmetrical relative to creation. I can remove it if you prefer.

**Comment by jkowalski** [comment]
Thank you!

**Pull request merged**
